name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: llwizard1024
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Move snake to output
        run: mkdir -p output && mv dist/snake.svg output/

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update contribution snake"
